#set(SDL2_INCLUDE_DIR ${SDL2_DIR}/include)

find_path(SDL2_INCLUDE_DIR SDL.h
	HINTS ${SDL2_DIR}
	PATH_SUFFIXES SDL2 include/SDL2 include
)

#[[
#]]
# Support both 32 and 64 bit builds
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(SDL2_LIBRARIES ${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2.lib;${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2main.lib)
else()
  set(SDL2_LIBRARIES ${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2.lib;${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2main.lib)
endif()
#[[
#]]


#[[
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
	set(VC_LIB_PATH_SUFFIX lib/x64)
else()
	set(VC_LIB_PATH_SUFFIX lib/x86)
endif()

find_library(SDL2_LIB
	NAMES SDL2
	HINTS ${SDL2_DIR}
	PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
)

find_library(SDL2MAIN_LIB
	NAMES SDL2main
	HINTS ${SDL2_DIR}
	PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
)

set(SDL2_LIBRARIES ${SDL2_LIB} ${SDL2MAIN_LIB})
#]]


#[[
find_library(SDL2_LIBRARIES
	NAMES SDL2
	HINTS ${SDL2_DIR}
	PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
)
#]]


# Find dlls
find_file(SDL2_DLL SDL2.dll
	HINTS ${SDL2_DIR}
	PATH_SUFFIXES bin ${VC_LIB_PATH_SUFFIX}
)
